### PR TITLE
lower deployment target from 9.3 -> 8.0

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by ianterrell** [comment]
Hi @AndrewSB,

Are you planning on using this in a project that supports iOS 8? I'd warn you that at this point we still consider Cordux to be at beta quality and it may change drastically over the next several months as we build out projects with it.

Thanks,
Ian

**Comment by AndrewSB** [comment]
Hey @ianterrell!

I'm using it for a project that supports iOS 8 currently, but I have absolutely no issues upping the project's deployment target to iOS 9 if need be.

My rationale on this PR was based on the fact that (currently) there's no additional work to support iOS 8.

I've also just invited you to a private repo (https://github.com/AndrewSB/wrytr) where I'm using Cordux for a side project.
At the very least I hope it can be an example for you to see how other people are using Cordux, and I'd love any feedback on the patterns I'm using if you have time 😄

**Comment by ianterrell** [comment]
Cool. For the time being then I think we'll keep it at 9. Right now we're just a small team working on it and minimizing support is helpful for us. :)

**Comment by AndrewSB** [comment]
that makes sense! Thanks @ianterrell

**Pull request closed without merging**
